"""empty message

Revision ID: 1407a74d1252
Revises: ce8dcefeaf17
Create Date: 2024-06-09 16:32:00.476777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1407a74d1252'
down_revision = 'ce8dcefeaf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('raw_material_request_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_raw_material_request',
    sa.Column('raw_material_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_request_id'], ['raw_material_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('raw_material_request_id', 'user_id')
    )
    op.create_table('raw_material_request_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_request_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.ForeignKeyConstraint(['raw_material_request_id'], ['raw_material_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_raw_material_request',
    sa.Column('raw_material_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_request_id'], ['raw_material_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('raw_material_request_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_raw_material_request')
    op.drop_table('raw_material_request_detail')
    op.drop_table('admin_raw_material_request')
    op.drop_table('raw_material_request')
    # ### end Alembic commands ###
