"""empty message

Revision ID: 23a9d43e6283
Revises: 
Create Date: 2025-10-30 08:57:21.711777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a9d43e6283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('registered_name', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=255), nullable=True),
    sa.Column('business_style', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=255), nullable=True),
    sa.Column('salesman', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('permanent_address', sa.String(), nullable=True),
    sa.Column('city_address', sa.String(), nullable=True),
    sa.Column('date_probationary', sa.String(), nullable=True),
    sa.Column('date_regular', sa.String(), nullable=True),
    sa.Column('employee_number', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('sss_number', sa.String(), nullable=True),
    sa.Column('phic_number', sa.String(), nullable=True),
    sa.Column('hdmf_number', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('contact_person_name', sa.String(), nullable=True),
    sa.Column('contact_person_relationship', sa.String(), nullable=True),
    sa.Column('contact_person_number', sa.String(), nullable=True),
    sa.Column('contact_person_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injection_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('injection_machine_name', sa.String(length=255), nullable=True),
    sa.Column('injection_machine_code', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lithography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lithography_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=255), nullable=True),
    sa.Column('label_code', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_label_adjustment_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_issuance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_label_issuance_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_label_return_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_status_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_product_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_product_component_name', sa.String(length=255), nullable=True),
    sa.Column('plastic_product_component_code', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_product_component_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_product_component_status_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_name', sa.String(length=255), nullable=True),
    sa.Column('plastic_raw_material_code', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_raw_material_adjustment_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_issuance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_raw_material_issuance_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_raw_material_return_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_status_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inhouse_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_code', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=255), nullable=True),
    sa.Column('default_price', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_tincan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('production_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('pass_word', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('staff', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('registered_name', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=255), nullable=True),
    sa.Column('business_style', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'user_id')
    )
    op.create_table('admin_department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'user_id')
    )
    op.create_table('admin_employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'user_id')
    )
    op.create_table('admin_injection_machine',
    sa.Column('injection_machine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['injection_machine_id'], ['injection_machine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('injection_machine_id', 'user_id')
    )
    op.create_table('admin_lithography',
    sa.Column('lithography_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_id'], ['lithography.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_id', 'user_id')
    )
    op.create_table('admin_measure',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('measure_id', 'user_id')
    )
    op.create_table('admin_operator',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('operator_id', 'user_id')
    )
    op.create_table('admin_plastic_label',
    sa.Column('plastic_label_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_id', 'user_id')
    )
    op.create_table('admin_plastic_label_adjustment',
    sa.Column('plastic_label_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_adjustment_id'], ['plastic_label_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_adjustment_id', 'user_id')
    )
    op.create_table('admin_plastic_label_issuance',
    sa.Column('plastic_label_issuance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_issuance_id'], ['plastic_label_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_issuance_id', 'user_id')
    )
    op.create_table('admin_plastic_label_return',
    sa.Column('plastic_label_return_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_return_id'], ['plastic_label_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_return_id', 'user_id')
    )
    op.create_table('admin_plastic_label_status',
    sa.Column('plastic_label_status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_status_id'], ['plastic_label_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_status_id', 'user_id')
    )
    op.create_table('admin_plastic_product_component',
    sa.Column('plastic_product_component_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_id'], ['plastic_product_component.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_id', 'user_id')
    )
    op.create_table('admin_plastic_product_component_status',
    sa.Column('plastic_product_component_status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_status_id'], ['plastic_product_component_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_status_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material',
    sa.Column('plastic_raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_adjustment',
    sa.Column('plastic_raw_material_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_adjustment_id'], ['plastic_raw_material_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_adjustment_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_issuance',
    sa.Column('plastic_raw_material_issuance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_issuance_id'], ['plastic_raw_material_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_issuance_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_return',
    sa.Column('plastic_raw_material_return_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_return_id'], ['plastic_raw_material_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_return_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_status',
    sa.Column('plastic_raw_material_status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_status_id'], ['plastic_raw_material_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_status_id', 'user_id')
    )
    op.create_table('admin_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    op.create_table('admin_production_tincan',
    sa.Column('production_tincan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_tincan_id'], ['production_tincan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('production_tincan_id', 'user_id')
    )
    op.create_table('admin_raw_material',
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('raw_material_id', 'user_id')
    )
    op.create_table('admin_sales_order_customer',
    sa.Column('sales_order_customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_customer_id'], ['sales_order_customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_order_customer_id', 'user_id')
    )
    op.create_table('admin_shift',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('shift_id', 'user_id')
    )
    op.create_table('admin_vendor',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'user_id')
    )
    op.create_table('delivery_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('delivery_receipt_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salesman', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('stacking', sa.String(), nullable=True),
    sa.Column('production_date', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_receipt_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('delivery_receipt_extra_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salesman', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issuance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('issuance_number', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('done', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lithography_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('lithography_receipt_number', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('lithography_id', sa.Integer(), nullable=False),
    sa.Column('sheet_received', sa.Integer(), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('additional_charge', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lithography_id'], ['lithography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_adjustment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_adjustment_id'], ['plastic_label_adjustment.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_issuance_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_issuance_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_issuance_id'], ['plastic_label_issuance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_label_receipt_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('packing_list', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('noted_by', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_return_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_return_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_status_id', sa.Integer(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_return_id'], ['plastic_label_return.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_status_id'], ['plastic_label_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_product_component_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_product_component_production_number', sa.String(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('injection_machine_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['injection_machine_id'], ['injection_machine.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_adjustment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_adjustment_id'], ['plastic_raw_material_adjustment.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_issuance_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_issuance_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_issuance_id'], ['plastic_raw_material_issuance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('plastic_raw_material_receipt_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('packing_list', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_return_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_return_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_status_id', sa.Integer(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_return_id'], ['plastic_raw_material_return.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_status_id'], ['plastic_raw_material_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_tincan_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_tincan_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['production_tincan_id'], ['production_tincan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('purchase_order_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('discount_note', sa.String(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('add_vat', sa.Float(), nullable=True),
    sa.Column('order_note', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('purchase_order_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('discount_note', sa.String(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('order_note', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('purchase_request_number', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('request_note', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('done', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiving_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('receiving_report_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('supporting_documents', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('sales_order_number', sa.String(), nullable=True),
    sa.Column('sales_order_customer_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sales_order_customer_id'], ['sales_order_customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'user_id')
    )
    op.create_table('user_department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'user_id')
    )
    op.create_table('user_employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'user_id')
    )
    op.create_table('user_injection_machine',
    sa.Column('injection_machine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['injection_machine_id'], ['injection_machine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('injection_machine_id', 'user_id')
    )
    op.create_table('user_lithography',
    sa.Column('lithography_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_id'], ['lithography.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_id', 'user_id')
    )
    op.create_table('user_measure',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('measure_id', 'user_id')
    )
    op.create_table('user_operator',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('operator_id', 'user_id')
    )
    op.create_table('user_plastic_label',
    sa.Column('plastic_label_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_id', 'user_id')
    )
    op.create_table('user_plastic_label_adjustment',
    sa.Column('plastic_label_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_adjustment_id'], ['plastic_label_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_adjustment_id', 'user_id')
    )
    op.create_table('user_plastic_label_issuance',
    sa.Column('plastic_label_issuance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_issuance_id'], ['plastic_label_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_issuance_id', 'user_id')
    )
    op.create_table('user_plastic_label_return',
    sa.Column('plastic_label_return_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_return_id'], ['plastic_label_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_return_id', 'user_id')
    )
    op.create_table('user_plastic_label_status',
    sa.Column('plastic_label_status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_status_id'], ['plastic_label_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_status_id', 'user_id')
    )
    op.create_table('user_plastic_product_component',
    sa.Column('plastic_product_component_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_id'], ['plastic_product_component.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_id', 'user_id')
    )
    op.create_table('user_plastic_product_component_status',
    sa.Column('plastic_product_component_status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_status_id'], ['plastic_product_component_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_status_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material',
    sa.Column('plastic_raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_adjustment',
    sa.Column('plastic_raw_material_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_adjustment_id'], ['plastic_raw_material_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_adjustment_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_issuance',
    sa.Column('plastic_raw_material_issuance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_issuance_id'], ['plastic_raw_material_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_issuance_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_return',
    sa.Column('plastic_raw_material_return_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_return_id'], ['plastic_raw_material_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_return_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_status',
    sa.Column('plastic_raw_material_status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_status_id'], ['plastic_raw_material_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_status_id', 'user_id')
    )
    op.create_table('user_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    op.create_table('user_production_tincan',
    sa.Column('production_tincan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_tincan_id'], ['production_tincan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('production_tincan_id', 'user_id')
    )
    op.create_table('user_raw_material',
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('raw_material_id', 'user_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sales_order_customer',
    sa.Column('sales_order_customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_customer_id'], ['sales_order_customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_order_customer_id', 'user_id')
    )
    op.create_table('user_shift',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('shift_id', 'user_id')
    )
    op.create_table('user_vendor',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'user_id')
    )
    op.create_table('admin_delivery_receipt',
    sa.Column('delivery_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_receipt_id'], ['delivery_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('delivery_receipt_id', 'user_id')
    )
    op.create_table('admin_delivery_receipt_extra',
    sa.Column('delivery_receipt_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_receipt_extra_id'], ['delivery_receipt_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('delivery_receipt_extra_id', 'user_id')
    )
    op.create_table('admin_issuance',
    sa.Column('issuance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('issuance_id', 'user_id')
    )
    op.create_table('admin_lithography_receipt',
    sa.Column('lithography_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_receipt_id'], ['lithography_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_receipt_id', 'user_id')
    )
    op.create_table('admin_plastic_label_receipt',
    sa.Column('plastic_label_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_receipt_id'], ['plastic_label_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_receipt_id', 'user_id')
    )
    op.create_table('admin_plastic_product_component_production',
    sa.Column('plastic_product_component_production_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_production_id'], ['plastic_product_component_production.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_production_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_receipt',
    sa.Column('plastic_raw_material_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_receipt_id'], ['plastic_raw_material_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_receipt_id', 'user_id')
    )
    op.create_table('admin_purchase_order',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id', 'user_id')
    )
    op.create_table('admin_purchase_order_extra',
    sa.Column('purchase_order_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_extra_id'], ['purchase_order_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_extra_id', 'user_id')
    )
    op.create_table('admin_purchase_request',
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_request_id', 'user_id')
    )
    op.create_table('admin_receiving_report',
    sa.Column('receiving_report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiving_report_id'], ['receiving_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('receiving_report_id', 'user_id')
    )
    op.create_table('admin_sales_order',
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_order_id', 'user_id')
    )
    op.create_table('delivery_receipt_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_receipt_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_receipt_id'], ['delivery_receipt.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_receipt_extra_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_receipt_extra_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_receipt_extra_id'], ['delivery_receipt_extra.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issuance_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuance_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuance.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_receipt_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_receipt_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_label_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_receipt_id'], ['plastic_label_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_product_component_production_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_product_component_production_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_product_component_id', sa.Integer(), nullable=False),
    sa.Column('plastic_product_component_status_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_product_component_id'], ['plastic_product_component.id'], ),
    sa.ForeignKeyConstraint(['plastic_product_component_production_id'], ['plastic_product_component_production.id'], ),
    sa.ForeignKeyConstraint(['plastic_product_component_status_id'], ['plastic_product_component_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_receipt_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_receipt_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.Integer(), nullable=False),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_receipt_id'], ['plastic_raw_material_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_number', sa.String(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_extra_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_number', sa.String(), nullable=True),
    sa.Column('purchase_order_extra_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_extra_id'], ['purchase_order_extra.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_request_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('date_needed', sa.String(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_request.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiving_report_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_number', sa.String(), nullable=True),
    sa.Column('receiving_report_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.ForeignKeyConstraint(['receiving_report_id'], ['receiving_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_po_number', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_delivery_receipt',
    sa.Column('delivery_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_receipt_id'], ['delivery_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('delivery_receipt_id', 'user_id')
    )
    op.create_table('user_delivery_receipt_extra',
    sa.Column('delivery_receipt_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_receipt_extra_id'], ['delivery_receipt_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('delivery_receipt_extra_id', 'user_id')
    )
    op.create_table('user_issuance',
    sa.Column('issuance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('issuance_id', 'user_id')
    )
    op.create_table('user_lithography_receipt',
    sa.Column('lithography_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_receipt_id'], ['lithography_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_receipt_id', 'user_id')
    )
    op.create_table('user_plastic_label_receipt',
    sa.Column('plastic_label_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_receipt_id'], ['plastic_label_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_receipt_id', 'user_id')
    )
    op.create_table('user_plastic_product_component_production',
    sa.Column('plastic_product_component_production_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_production_id'], ['plastic_product_component_production.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_production_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_receipt',
    sa.Column('plastic_raw_material_receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_receipt_id'], ['plastic_raw_material_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_receipt_id', 'user_id')
    )
    op.create_table('user_purchase_order',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id', 'user_id')
    )
    op.create_table('user_purchase_order_extra',
    sa.Column('purchase_order_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_extra_id'], ['purchase_order_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_extra_id', 'user_id')
    )
    op.create_table('user_purchase_request',
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_request_id', 'user_id')
    )
    op.create_table('user_receiving_report',
    sa.Column('receiving_report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiving_report_id'], ['receiving_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('receiving_report_id', 'user_id')
    )
    op.create_table('user_sales_order',
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_order_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sales_order')
    op.drop_table('user_receiving_report')
    op.drop_table('user_purchase_request')
    op.drop_table('user_purchase_order_extra')
    op.drop_table('user_purchase_order')
    op.drop_table('user_plastic_raw_material_receipt')
    op.drop_table('user_plastic_product_component_production')
    op.drop_table('user_plastic_label_receipt')
    op.drop_table('user_lithography_receipt')
    op.drop_table('user_issuance')
    op.drop_table('user_delivery_receipt_extra')
    op.drop_table('user_delivery_receipt')
    op.drop_table('sales_order_detail')
    op.drop_table('receiving_report_detail')
    op.drop_table('purchase_request_detail')
    op.drop_table('purchase_order_extra_detail')
    op.drop_table('purchase_order_detail')
    op.drop_table('plastic_raw_material_receipt_detail')
    op.drop_table('plastic_product_component_production_detail')
    op.drop_table('plastic_label_receipt_detail')
    op.drop_table('issuance_detail')
    op.drop_table('delivery_receipt_extra_detail')
    op.drop_table('delivery_receipt_detail')
    op.drop_table('admin_sales_order')
    op.drop_table('admin_receiving_report')
    op.drop_table('admin_purchase_request')
    op.drop_table('admin_purchase_order_extra')
    op.drop_table('admin_purchase_order')
    op.drop_table('admin_plastic_raw_material_receipt')
    op.drop_table('admin_plastic_product_component_production')
    op.drop_table('admin_plastic_label_receipt')
    op.drop_table('admin_lithography_receipt')
    op.drop_table('admin_issuance')
    op.drop_table('admin_delivery_receipt_extra')
    op.drop_table('admin_delivery_receipt')
    op.drop_table('user_vendor')
    op.drop_table('user_shift')
    op.drop_table('user_sales_order_customer')
    op.drop_table('user_role')
    op.drop_table('user_raw_material')
    op.drop_table('user_production_tincan')
    op.drop_table('user_product')
    op.drop_table('user_plastic_raw_material_status')
    op.drop_table('user_plastic_raw_material_return')
    op.drop_table('user_plastic_raw_material_issuance')
    op.drop_table('user_plastic_raw_material_adjustment')
    op.drop_table('user_plastic_raw_material')
    op.drop_table('user_plastic_product_component_status')
    op.drop_table('user_plastic_product_component')
    op.drop_table('user_plastic_label_status')
    op.drop_table('user_plastic_label_return')
    op.drop_table('user_plastic_label_issuance')
    op.drop_table('user_plastic_label_adjustment')
    op.drop_table('user_plastic_label')
    op.drop_table('user_operator')
    op.drop_table('user_measure')
    op.drop_table('user_lithography')
    op.drop_table('user_injection_machine')
    op.drop_table('user_employee')
    op.drop_table('user_department')
    op.drop_table('user_customer')
    op.drop_table('sales_order')
    op.drop_table('receiving_report')
    op.drop_table('purchase_request')
    op.drop_table('purchase_order_extra')
    op.drop_table('purchase_order')
    op.drop_table('production_tincan_detail')
    op.drop_table('plastic_raw_material_return_detail')
    op.drop_table('plastic_raw_material_receipt')
    op.drop_table('plastic_raw_material_issuance_detail')
    op.drop_table('plastic_raw_material_adjustment_detail')
    op.drop_table('plastic_product_component_production')
    op.drop_table('plastic_label_return_detail')
    op.drop_table('plastic_label_receipt')
    op.drop_table('plastic_label_issuance_detail')
    op.drop_table('plastic_label_adjustment_detail')
    op.drop_table('lithography_receipt')
    op.drop_table('issuance')
    op.drop_table('delivery_receipt_extra')
    op.drop_table('delivery_receipt')
    op.drop_table('admin_vendor')
    op.drop_table('admin_shift')
    op.drop_table('admin_sales_order_customer')
    op.drop_table('admin_raw_material')
    op.drop_table('admin_production_tincan')
    op.drop_table('admin_product')
    op.drop_table('admin_plastic_raw_material_status')
    op.drop_table('admin_plastic_raw_material_return')
    op.drop_table('admin_plastic_raw_material_issuance')
    op.drop_table('admin_plastic_raw_material_adjustment')
    op.drop_table('admin_plastic_raw_material')
    op.drop_table('admin_plastic_product_component_status')
    op.drop_table('admin_plastic_product_component')
    op.drop_table('admin_plastic_label_status')
    op.drop_table('admin_plastic_label_return')
    op.drop_table('admin_plastic_label_issuance')
    op.drop_table('admin_plastic_label_adjustment')
    op.drop_table('admin_plastic_label')
    op.drop_table('admin_operator')
    op.drop_table('admin_measure')
    op.drop_table('admin_lithography')
    op.drop_table('admin_injection_machine')
    op.drop_table('admin_employee')
    op.drop_table('admin_department')
    op.drop_table('admin_customer')
    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('shift')
    op.drop_table('sales_order_customer')
    op.drop_table('role')
    op.drop_table('raw_material')
    op.drop_table('production_tincan')
    op.drop_table('product')
    op.drop_table('plastic_raw_material_status')
    op.drop_table('plastic_raw_material_return')
    op.drop_table('plastic_raw_material_issuance')
    op.drop_table('plastic_raw_material_adjustment')
    op.drop_table('plastic_raw_material')
    op.drop_table('plastic_product_component_status')
    op.drop_table('plastic_product_component')
    op.drop_table('plastic_label_status')
    op.drop_table('plastic_label_return')
    op.drop_table('plastic_label_issuance')
    op.drop_table('plastic_label_adjustment')
    op.drop_table('plastic_label')
    op.drop_table('operator')
    op.drop_table('measure')
    op.drop_table('lithography')
    op.drop_table('injection_machine')
    op.drop_table('employee')
    op.drop_table('department')
    op.drop_table('customer')
    # ### end Alembic commands ###
