"""empty message

Revision ID: 25e34dd1da8b
Revises: 8a66eba9c233
Create Date: 2026-02-15 10:40:50.898095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '25e34dd1da8b'
down_revision = '8a66eba9c233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    existing_tables = inspector.get_table_names()

    # ---- Drop dependent tables first (order matters) ----
    if 'admin_job_order' in existing_tables:
        op.drop_table('admin_job_order')

    if 'user_job_order' in existing_tables:
        op.drop_table('user_job_order')

    if 'job_order_detail' in existing_tables:
        op.drop_table('job_order_detail')

    if 'job_order' in existing_tables:
        op.drop_table('job_order')

    op.create_table('job_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('job_order_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_reference_number', sa.String(), nullable=True),
    sa.Column('order_note', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_job_order',
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('job_order_id', 'user_id')
    )
    op.create_table('job_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_order.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_job_order',
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('job_order_id', 'user_id')
    )
    with op.batch_alter_table('user_role') as batch_op:
        batch_op.create_foreign_key(
            "fk_user_role_user",
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            "fk_user_role_role",
            "role",
            ["role_id"],
            ["id"],
            ondelete="CASCADE"
        )


    # ### end Alembic commands ###


def downgrade():

    # ---- Revert user_role foreign keys ----
    with op.batch_alter_table('user_role') as batch_op:

        # Drop CASCADE foreign keys (must match names used in upgrade)
        batch_op.drop_constraint(
            "fk_user_role_user",
            type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_user_role_role",
            type_="foreignkey"
        )

        # Recreate original foreign keys (without cascade)
        batch_op.create_foreign_key(
            "fk_user_role_user",
            "user",
            ["user_id"],
            ["id"]
        )
        batch_op.create_foreign_key(
            "fk_user_role_role",
            "role",
            ["role_id"],
            ["id"]
        )

    # ---- Drop tables in correct dependency order ----
    op.drop_table('user_job_order')
    op.drop_table('job_order_detail')
    op.drop_table('admin_job_order')
    op.drop_table('job_order')

