"""empty message

Revision ID: 3d5da942ff08
Revises: 1603c16f860b
Create Date: 2024-06-09 10:47:41.110724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5da942ff08'
down_revision = '1603c16f860b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_name', sa.String(length=255), nullable=True),
    sa.Column('raw_material_code', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_raw_material',
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('raw_material_id', 'user_id')
    )
    op.create_table('user_raw_material',
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('raw_material_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_raw_material')
    op.drop_table('admin_raw_material')
    op.drop_table('raw_material')
    # ### end Alembic commands ###
