"""empty message

Revision ID: 4a6dac87909b
Revises: 642bb36ecd1b
Create Date: 2026-02-10 07:38:20.301839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6dac87909b'
down_revision = '642bb36ecd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('inhouse_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inhouse_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
