"""empty message

Revision ID: 642bb36ecd1b
Revises: c1515111af4e
Create Date: 2025-12-19 17:19:16.966534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642bb36ecd1b'
down_revision = 'c1515111af4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plastic_raw_material_return')
    op.drop_table('admin_plastic_label_status')
    op.drop_table('purchase_order_extra')
    op.drop_table('plastic_product_component_status')
    op.drop_table('admin_plastic_raw_material_return')
    op.drop_table('admin_plastic_product_component_status')
    op.drop_table('plastic_raw_material_issuance_detail')
    op.drop_table('plastic_label_receipt')
    op.drop_table('issuance')
    op.drop_table('user_plastic_product_component_status')
    op.drop_table('plastic_label_adjustment_detail')
    op.drop_table('plastic_label_receipt_detail')
    op.drop_table('production_tincan_detail')
    op.drop_table('purchase_order_extra_detail')
    op.drop_table('user_plastic_raw_material_receipt')
    op.drop_table('user_shift')
    op.drop_table('sales_order')
    op.drop_table('user_plastic_product_component')
    op.drop_table('plastic_raw_material')
    op.drop_table('user_plastic_label_adjustment')
    op.drop_table('lithography')
    op.drop_table('plastic_raw_material_receipt_detail')
    op.drop_table('user_plastic_label')
    op.drop_table('admin_plastic_label_issuance')
    op.drop_table('admin_plastic_product_component')
    op.drop_table('plastic_label_return_detail')
    op.drop_table('plastic_label_adjustment')
    op.drop_table('user_injection_machine')
    op.drop_table('user_lithography')
    op.drop_table('user_sales_order')
    op.drop_table('admin_plastic_raw_material_issuance')
    op.drop_table('admin_shift')
    op.drop_table('user_purchase_order_extra')
    op.drop_table('user_lithography_receipt')
    op.drop_table('user_plastic_raw_material_return')
    op.drop_table('admin_lithography_receipt')
    op.drop_table('admin_employee')
    op.drop_table('plastic_label')
    op.drop_table('user_plastic_raw_material_issuance')
    op.drop_table('user_plastic_label_status')
    op.drop_table('admin_plastic_raw_material_adjustment')
    op.drop_table('user_plastic_raw_material_adjustment')
    op.drop_table('plastic_raw_material_status')
    op.drop_table('plastic_label_return')
    op.drop_table('plastic_label_issuance_detail')
    op.drop_table('shift')
    op.drop_table('user_plastic_raw_material')
    op.drop_table('plastic_raw_material_adjustment_detail')
    op.drop_table('issuance_detail')
    op.drop_table('admin_injection_machine')
    op.drop_table('plastic_raw_material_return_detail')
    op.drop_table('user_plastic_label_return')
    op.drop_table('admin_plastic_raw_material')
    op.drop_table('user_plastic_label_issuance')
    op.drop_table('admin_plastic_label')
    op.drop_table('plastic_label_issuance')
    op.drop_table('admin_plastic_label_return')
    op.drop_table('user_plastic_raw_material_status')
    op.drop_table('user_production_tincan')
    op.drop_table('admin_lithography')
    op.drop_table('admin_plastic_product_component_production')
    op.drop_table('employee')
    op.drop_table('user_issuance')
    op.drop_table('plastic_raw_material_receipt')
    op.drop_table('lithography_receipt')
    op.drop_table('plastic_raw_material_issuance')
    op.drop_table('user_operator')
    op.drop_table('admin_production_tincan')
    op.drop_table('operator')
    op.drop_table('admin_sales_order')
    op.drop_table('admin_plastic_label_adjustment')
    op.drop_table('user_employee')
    op.drop_table('production_tincan')
    op.drop_table('admin_plastic_label_receipt')
    op.drop_table('sales_order_detail')
    op.drop_table('plastic_product_component_production_detail')
    op.drop_table('admin_plastic_raw_material_receipt')
    op.drop_table('user_plastic_product_component_production')
    op.drop_table('injection_machine')
    op.drop_table('plastic_label_status')
    op.drop_table('plastic_raw_material_adjustment')
    op.drop_table('plastic_product_component_production')
    op.drop_table('user_plastic_label_receipt')
    op.drop_table('admin_plastic_raw_material_status')
    op.drop_table('admin_purchase_order_extra')
    op.drop_table('admin_operator')
    op.drop_table('plastic_product_component')
    op.drop_table('admin_issuance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_issuance',
    sa.Column('issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('issuance_id', 'user_id')
    )
    op.create_table('plastic_product_component',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_product_component_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('plastic_product_component_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_operator',
    sa.Column('operator_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('operator_id', 'user_id')
    )
    op.create_table('admin_purchase_order_extra',
    sa.Column('purchase_order_extra_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_extra_id'], ['purchase_order_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_extra_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_status',
    sa.Column('plastic_raw_material_status_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_status_id'], ['plastic_raw_material_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_status_id', 'user_id')
    )
    op.create_table('user_plastic_label_receipt',
    sa.Column('plastic_label_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_receipt_id'], ['plastic_label_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_receipt_id', 'user_id')
    )
    op.create_table('plastic_product_component_production',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_product_component_production_number', sa.VARCHAR(), nullable=True),
    sa.Column('shift_id', sa.INTEGER(), nullable=False),
    sa.Column('injection_machine_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['injection_machine_id'], ['injection_machine.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_adjustment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_raw_material_adjustment_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_status_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injection_machine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('injection_machine_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('injection_machine_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plastic_product_component_production',
    sa.Column('plastic_product_component_production_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_production_id'], ['plastic_product_component_production.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_production_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_receipt',
    sa.Column('plastic_raw_material_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_receipt_id'], ['plastic_raw_material_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_receipt_id', 'user_id')
    )
    op.create_table('plastic_product_component_production_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_product_component_production_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_product_component_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_product_component_status_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_product_component_id'], ['plastic_product_component.id'], ),
    sa.ForeignKeyConstraint(['plastic_product_component_production_id'], ['plastic_product_component_production.id'], ),
    sa.ForeignKeyConstraint(['plastic_product_component_status_id'], ['plastic_product_component_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_po_number', sa.VARCHAR(), nullable=True),
    sa.Column('delivery_date', sa.VARCHAR(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_plastic_label_receipt',
    sa.Column('plastic_label_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_receipt_id'], ['plastic_label_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_receipt_id', 'user_id')
    )
    op.create_table('production_tincan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('production_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.Column('prepared_by', sa.VARCHAR(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_employee',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'user_id')
    )
    op.create_table('admin_plastic_label_adjustment',
    sa.Column('plastic_label_adjustment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_adjustment_id'], ['plastic_label_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_adjustment_id', 'user_id')
    )
    op.create_table('admin_sales_order',
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_order_id', 'user_id')
    )
    op.create_table('operator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_production_tincan',
    sa.Column('production_tincan_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['production_tincan_id'], ['production_tincan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('production_tincan_id', 'user_id')
    )
    op.create_table('user_operator',
    sa.Column('operator_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('operator_id', 'user_id')
    )
    op.create_table('plastic_raw_material_issuance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_raw_material_issuance_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lithography_receipt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('lithography_receipt_number', sa.VARCHAR(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=True),
    sa.Column('lithography_id', sa.INTEGER(), nullable=False),
    sa.Column('sheet_received', sa.INTEGER(), nullable=True),
    sa.Column('outs', sa.INTEGER(), nullable=True),
    sa.Column('net_amount', sa.FLOAT(), nullable=True),
    sa.Column('additional_charge', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['lithography_id'], ['lithography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_receipt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_raw_material_receipt_number', sa.VARCHAR(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('packing_list', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_issuance',
    sa.Column('issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('issuance_id', 'user_id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), nullable=True),
    sa.Column('permanent_address', sa.VARCHAR(), nullable=True),
    sa.Column('city_address', sa.VARCHAR(), nullable=True),
    sa.Column('date_probationary', sa.VARCHAR(), nullable=True),
    sa.Column('date_regular', sa.VARCHAR(), nullable=True),
    sa.Column('employee_number', sa.VARCHAR(), nullable=True),
    sa.Column('tin', sa.VARCHAR(), nullable=True),
    sa.Column('sss_number', sa.VARCHAR(), nullable=True),
    sa.Column('phic_number', sa.VARCHAR(), nullable=True),
    sa.Column('hdmf_number', sa.VARCHAR(), nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), nullable=True),
    sa.Column('email_address', sa.VARCHAR(), nullable=True),
    sa.Column('contact_person_name', sa.VARCHAR(), nullable=True),
    sa.Column('contact_person_relationship', sa.VARCHAR(), nullable=True),
    sa.Column('contact_person_number', sa.VARCHAR(), nullable=True),
    sa.Column('contact_person_address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_plastic_product_component_production',
    sa.Column('plastic_product_component_production_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_production_id'], ['plastic_product_component_production.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_production_id', 'user_id')
    )
    op.create_table('admin_lithography',
    sa.Column('lithography_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_id'], ['lithography.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_id', 'user_id')
    )
    op.create_table('user_production_tincan',
    sa.Column('production_tincan_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['production_tincan_id'], ['production_tincan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('production_tincan_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_status',
    sa.Column('plastic_raw_material_status_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_status_id'], ['plastic_raw_material_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_status_id', 'user_id')
    )
    op.create_table('admin_plastic_label_return',
    sa.Column('plastic_label_return_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_return_id'], ['plastic_label_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_return_id', 'user_id')
    )
    op.create_table('plastic_label_issuance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_label_issuance_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_plastic_label',
    sa.Column('plastic_label_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_id', 'user_id')
    )
    op.create_table('user_plastic_label_issuance',
    sa.Column('plastic_label_issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_issuance_id'], ['plastic_label_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_issuance_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material',
    sa.Column('plastic_raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_id', 'user_id')
    )
    op.create_table('user_plastic_label_return',
    sa.Column('plastic_label_return_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_return_id'], ['plastic_label_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_return_id', 'user_id')
    )
    op.create_table('plastic_raw_material_return_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_return_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_status_id', sa.INTEGER(), nullable=True),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_return_id'], ['plastic_raw_material_return.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_status_id'], ['plastic_raw_material_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_injection_machine',
    sa.Column('injection_machine_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['injection_machine_id'], ['injection_machine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('injection_machine_id', 'user_id')
    )
    op.create_table('issuance_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuance.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_adjustment_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_adjustment_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_adjustment_id'], ['plastic_raw_material_adjustment.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plastic_raw_material',
    sa.Column('plastic_raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_id', 'user_id')
    )
    op.create_table('shift',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shift_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_issuance_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_issuance_id'], ['plastic_label_issuance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_return',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_label_return_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_status_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plastic_raw_material_adjustment',
    sa.Column('plastic_raw_material_adjustment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_adjustment_id'], ['plastic_raw_material_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_adjustment_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_adjustment',
    sa.Column('plastic_raw_material_adjustment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_adjustment_id'], ['plastic_raw_material_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_adjustment_id', 'user_id')
    )
    op.create_table('user_plastic_label_status',
    sa.Column('plastic_label_status_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_status_id'], ['plastic_label_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_status_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_issuance',
    sa.Column('plastic_raw_material_issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_issuance_id'], ['plastic_raw_material_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_issuance_id', 'user_id')
    )
    op.create_table('plastic_label',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('label_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_employee',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'user_id')
    )
    op.create_table('admin_lithography_receipt',
    sa.Column('lithography_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_receipt_id'], ['lithography_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_receipt_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_return',
    sa.Column('plastic_raw_material_return_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_return_id'], ['plastic_raw_material_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_return_id', 'user_id')
    )
    op.create_table('user_lithography_receipt',
    sa.Column('lithography_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_receipt_id'], ['lithography_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_receipt_id', 'user_id')
    )
    op.create_table('user_purchase_order_extra',
    sa.Column('purchase_order_extra_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_extra_id'], ['purchase_order_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_extra_id', 'user_id')
    )
    op.create_table('admin_shift',
    sa.Column('shift_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('shift_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_issuance',
    sa.Column('plastic_raw_material_issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_issuance_id'], ['plastic_raw_material_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_issuance_id', 'user_id')
    )
    op.create_table('user_sales_order',
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_order_id', 'user_id')
    )
    op.create_table('user_lithography',
    sa.Column('lithography_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lithography_id'], ['lithography.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lithography_id', 'user_id')
    )
    op.create_table('user_injection_machine',
    sa.Column('injection_machine_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['injection_machine_id'], ['injection_machine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('injection_machine_id', 'user_id')
    )
    op.create_table('plastic_label_adjustment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_label_adjustment_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_return_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_return_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_status_id', sa.INTEGER(), nullable=True),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_return_id'], ['plastic_label_return.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_status_id'], ['plastic_label_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_plastic_product_component',
    sa.Column('plastic_product_component_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_id'], ['plastic_product_component.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_id', 'user_id')
    )
    op.create_table('admin_plastic_label_issuance',
    sa.Column('plastic_label_issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_issuance_id'], ['plastic_label_issuance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_issuance_id', 'user_id')
    )
    op.create_table('user_plastic_label',
    sa.Column('plastic_label_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_id', 'user_id')
    )
    op.create_table('plastic_raw_material_receipt_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_receipt_id'], ['plastic_raw_material_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lithography',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lithography_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plastic_label_adjustment',
    sa.Column('plastic_label_adjustment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_adjustment_id'], ['plastic_label_adjustment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_adjustment_id', 'user_id')
    )
    op.create_table('plastic_raw_material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('plastic_raw_material_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plastic_product_component',
    sa.Column('plastic_product_component_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_id'], ['plastic_product_component.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_id', 'user_id')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('sales_order_number', sa.VARCHAR(), nullable=True),
    sa.Column('sales_order_customer_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['sales_order_customer_id'], ['sales_order_customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shift',
    sa.Column('shift_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('shift_id', 'user_id')
    )
    op.create_table('user_plastic_raw_material_receipt',
    sa.Column('plastic_raw_material_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_receipt_id'], ['plastic_raw_material_receipt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_receipt_id', 'user_id')
    )
    op.create_table('purchase_order_extra_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_request_number', sa.VARCHAR(), nullable=True),
    sa.Column('purchase_order_extra_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_extra_id'], ['purchase_order_extra.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_tincan_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('production_tincan_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['production_tincan_id'], ['production_tincan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_receipt_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_receipt_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_receipt_id'], ['plastic_label_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_adjustment_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_adjustment_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_label_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_adjustment_id'], ['plastic_label_adjustment.id'], ),
    sa.ForeignKeyConstraint(['plastic_label_id'], ['plastic_label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plastic_product_component_status',
    sa.Column('plastic_product_component_status_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_status_id'], ['plastic_product_component_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_status_id', 'user_id')
    )
    op.create_table('issuance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('issuance_number', sa.VARCHAR(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.Column('requested_by', sa.VARCHAR(), nullable=True),
    sa.Column('prepared_by', sa.VARCHAR(), nullable=True),
    sa.Column('checked_by', sa.VARCHAR(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('done', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_label_receipt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_label_receipt_number', sa.VARCHAR(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('packing_list', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('reported_by', sa.VARCHAR(), nullable=True),
    sa.Column('received_by', sa.VARCHAR(), nullable=True),
    sa.Column('noted_by', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_raw_material_issuance_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_issuance_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('measure_id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('side_note', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_id'], ['plastic_raw_material.id'], ),
    sa.ForeignKeyConstraint(['plastic_raw_material_issuance_id'], ['plastic_raw_material_issuance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_plastic_product_component_status',
    sa.Column('plastic_product_component_status_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_product_component_status_id'], ['plastic_product_component_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_product_component_status_id', 'user_id')
    )
    op.create_table('admin_plastic_raw_material_return',
    sa.Column('plastic_raw_material_return_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_raw_material_return_id'], ['plastic_raw_material_return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_raw_material_return_id', 'user_id')
    )
    op.create_table('plastic_product_component_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plastic_product_component_status_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_extra',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('purchase_order_number', sa.VARCHAR(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('discount_note', sa.VARCHAR(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('order_note', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.Column('requested_by', sa.VARCHAR(), nullable=True),
    sa.Column('prepared_by', sa.VARCHAR(), nullable=True),
    sa.Column('checked_by', sa.VARCHAR(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('terms', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_plastic_label_status',
    sa.Column('plastic_label_status_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_label_status_id'], ['plastic_label_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plastic_label_status_id', 'user_id')
    )
    op.create_table('plastic_raw_material_return',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.VARCHAR(), nullable=True),
    sa.Column('plastic_raw_material_return_number', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.VARCHAR(), nullable=True),
    sa.Column('cancelled', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
