"""empty message

Revision ID: 68e05a94bfc7
Revises: 084b523aff5e
Create Date: 2024-06-16 11:23:21.504163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e05a94bfc7'
down_revision = '084b523aff5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_detail', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###
