"""empty message

Revision ID: 8a66eba9c233
Revises: 4a6dac87909b
Create Date: 2026-02-11 00:10:17.735123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a66eba9c233'
down_revision = '4a6dac87909b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_material_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_detail', schema=None) as batch_op:
        batch_op.drop_column('raw_material_description')

    # ### end Alembic commands ###
