"""empty message

Revision ID: c1515111af4e
Revises: 13c4fde9e049
Create Date: 2025-12-17 05:30:03.025034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1515111af4e'
down_revision = '13c4fde9e049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receiving_report_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receiving_report_detail', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
