"""empty message

Revision ID: cf85d47ac9ae
Revises: 25e34dd1da8b
Create Date: 2026-02-17 12:09:53.728805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf85d47ac9ae'
down_revision = '25e34dd1da8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_receipt_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_order_number', sa.String(), nullable=True))

    with op.batch_alter_table('delivery_receipt_extra_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_order_number', sa.String(), nullable=True))

    with op.batch_alter_table('job_order_detail', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('delivery_receipt_extra_detail', schema=None) as batch_op:
        batch_op.drop_column('job_order_number')

    with op.batch_alter_table('delivery_receipt_detail', schema=None) as batch_op:
        batch_op.drop_column('job_order_number')

    # ### end Alembic commands ###
